#データベースのパス
#相対座標が利用できます。
database:
  path: "./eye.db"
  logPath: "./log.db"
  learnPath: "./learn.db"

# Please add a language config setting

# This will change the plugin's default language.
# Options: jp, en
# lang: jp


#NPC Related Config
#npc関係のコンフィグです。
npc:
  #指定された秒数、NPCを召喚します。
  #秒数が短いとその中でのVL評価を行います。
  
 # Summons NPCs for the specified number of seconds.
 #If the number of seconds is short, VL evaluation will be performed within that time.
  seconds: 5


  #NPCの速度などを変えるとき、微調整してください。
  #別の値に指定する場合、適切な値でないとIssue 17に対応できなくなる可能性があります。
  
 # Make fine adjustments when changing the speed of #NPCs.
  #If you specify a different value, it may not be possible to support Issue 17 unless it is an appropriate value.
  time: 0.3

  #NPCのプレイヤーからの半径を指定します。
  #この値が最も安定している値ですが、ハッククライアントによってはKillAuraの半径を変更している場合もあります。
  
  #Specifies the radius from the NPC player.
  #This is the most stable value, but some hacked clients may have changed the radius of killaura.
  range: 2.1

  #NPCがWaveを描くかどうかを指定します。
  #falseにした場合、NPCはWaveを描かなくなりIssue 17に対応できなくなります。
  
  #Specifies whether #NPCs draw Waves.
 #If set to #false, NPCs will not draw Waves and will not be able to support Issue 17.
  wave: true

  #Waveの最小単位を指定します。
  #小さいほど動作が大きくなります。
  
 #Specify the minimum unit of Wave.
  #The smaller the size, the larger the operation.
  waveMin: 0.3

  #Panic NPCのプレイヤーからの半径を指定します。
  #Panic NPCの場合、通常のNPCと異なり半径が大きいとうまく動作しない可能性があります。

  #Panic Specifies the radius of the NPC from the player.
  #In the case of Panic NPC, unlike a normal NPC, it may not work well if the radius is large.
  panicRange: 1.5

  kill: 3

  #NPCの学習係数を指定します。
  #大きいほどニューラルネットワークでの処理の回数が少なくなりますが、精度は低くなります。サーバースペックに合わせて適切な値に変更してください。
  #Doubleのため小数第一位以降も設定可能です。
  
  #Specify the learning factor of NPC.
  #The larger the value, the less the number of processes in the neural network, but the lower the accuracy. Change it to an appropriate value according to the server specifications.
  #Since it is Double, it can be set after the first decimal place.
  learn: 0.3

  speed:
    wave: true
    waveRange: 0.03

mod:
  tracking:
    ##有効/無効 
    ## Set as Enabled or Disabled
    enabled: true
    #CompassTracker3000™のトラックチックです。
    # CompassTracker 3000 ™ track tick.
    trackTicks: 10

kick:
  delay: 2
  #プレイヤーがキックされるときに雷を召喚するやつです。
  #Summon lightning when user is kicked?
  lightning: true
#Default value when data up to Kick is not found
 #Kickまでのデータが見つからない場合のデフォルト値
  defaultKick: 25

message:
 # Messages that are compatible with the 'Hypixel Lynx' mod such as reports.
  lynx: true

autoMessage:
  #定期メッセージの有効/無効です  
#Periodic message enabled / disabled
  enabled: true

  #定期メッセージの周期です。(分指定)
#Periodic message cycle. (Specify minutes)
  time: 15

#スキンのUUIDセットです。
#ここにプレイヤーのUUIDを指定すれば、そのプレイヤーのスキンが使用されます。
#Skin UUID set.
#If you specify a player's UUID here, that player's skin will be used.
skins:
  - 6b93a8e658ee4794b69a56a3c2287010
  - 36f2cdbc77d545c7a205f5e8e6c0fb3b
  - 1fdd7771d09c407e9e6f86f8efab5604
  - eee5a0b7db174398abf0d462a2a0d910
  - f53127e597ad4fbfaa25ff7b18f156ef
  - 36f2cdbc77d545c7a205f5e8e6c0fb3b
  - 556ad16a459a46f29dbc6838906d1bf2
  - 6b93a8e658ee4794b69a56a3c2287010
  - 2fc54874b6134996b7512cbe85f04ea8
  - f7c77d999f154a66a87dc4a51ef30d19
  - 03b8fa5ac6774410be3081de2ccf490b
  - 95f9ec2297e84a5d89216b5c05029f12
  - a98e94094f014e58b07956e9640bc8d9
  - 10bd5a621b36458da4a474df6b9b95be
  - 07fe4381aaa24633bae183e58c5cc85b
  - b339457baf3c439680fc33c7a01398e8
  - 9f76cdc4c9004e34947a5f7615e07fde
  - 69e5aea0dd5e4cf88fcad8b4dd8b2243
  - 4e5959217b894ead96b9c50a4256da1e
  - c52fafa6e2234bddb884b39f641a4cf4
